<div
    class="{{$wrapperClasses}}"
    style="{{$wrapperStyle}}"
    data-laravel-image-wrapper
>
    @include('laravel-image::sizer')
    @include('laravel-image::placeholder')
    @include('laravel-image::main-image')
</div>
